### ISSUE TITLE
Delete

### ISSUE THREAD

**Issue by ghost** [fwestenberg/stookalert#4]
delete

**Comment by YRRK** [comment]
Maybe the RIVM website was down. I see it now works again. Closing this case.

**Comment by fwestenberg** [comment]
Thanks for closing. I qasn't able to reproduce this situation. Working fine here. :-)

**Comment by YRRK** [comment]
The issue is not always. It comes and goes. 

-- 
YRRK
Furkabaan 677
3524 ZG Utrecht
Tel: 06-20121418
Eml: info@yrrk.nl
KvK: 32098857

> Op 14 mrt. 2020 om 10:56 heeft fwestenberg <notifications@github.com> het volgende geschreven:
> 

﻿
Thanks for closing. I qasn't able to reproduce this situation. Working fine here. :-)
